name: CI Pipeline

on: [push, pull_request]  # Run on push & PRs

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use Ubuntu runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Get the repository code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pytest flake8  # Install testing framework

      - name: Run tests
        run: pytest  # Run all tests

      - name: Run linting
        run: flake8 .
